workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: 'com.example.myapp'
    scripts:
      - name: Install npm dependencies
        script: npm install
      - name: Add Android platform
        script: npx cap add android
      - name: Sync Capacitor assets
        script: npx cap sync
      - name: Build Android debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
