workflows:
  android-workflow:
    name: Build JARVIS Android APK
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 21  # Capacitor 8 works best with Java 21 on Codemagic
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dukeoghenenfejiroduke@gmail.com  # Replace or remove
