workflows:
  android:
    name: Build JARVIS Android APK
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 17  # Forces Java 17 to fix "invalid source release 21"
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dukeoghenefejiroduke@gmail.com  # Replace or remove this line
