workflows:
  android:
    name: Build JARVIS Android APK
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: latest
      npm: latest
     android_sdk: latest 
     java: 17   # Add this line
  android_sdk: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dukeoghenefejiroduke@gmail.com   # Change to your email (optional)
